exp_name: 'mpa'
device: ["mocap_vel"]
measurement_tp: ['pre']
pain_groups: ["healthy", "shoulder_neck"]
pca_analysis:
  check_requirements: False
  distributions_plotted: True
  create_general_plots: False
  check_ttest_distribution: False
  rotation_method: 'varimax'
  scaler_type: 'standard_scaler'
  nr_components: 100
  test_t_test_assumptions: True
  t_test_assumptions_relevant: True
  t_test_distribution_type: 'normal_distribution'
lda_analysis:
  lda_nr_components: 10
  lda_validation_type: 'strat_group_k_fold'
  lda_splits: 3
  lda_scaler_type: 'standard_scaler'
  lda_imputation_type: 'None'
  lda_imputer_parameter: 'None'
  lda_repeats: 100
database:
  path: "data/my_database.db"